"""
Document ingestion.

Responsible for loading raw files (PDF, TXT, DOCX) from the /data folder and
turning them into a normalized in-memory representation:

    Page = {
        "source": "renewable_energy.txt",
        "page_number": 1,          # 1 for plain text/docx (no pages), N for PDFs
        "text": "cleaned page text ..."
    }

Cleaning here is intentionally conservative: we strip obvious page-number-only
lines and excessive whitespace, but we do not attempt aggressive header/footer
removal since that is highly document-specific. For the PDF in this project's
sample corpus (generated by reportlab), extracted text is already clean.
"""

import re
from pathlib import Path
from typing import List, Dict

import pdfplumber
from docx import Document as DocxDocument

SUPPORTED_EXTENSIONS = {".pdf", ".txt", ".docx"}


def _clean_text(text: str) -> str:
    """Strip likely page-number-only lines and collapse excess whitespace."""
    lines = text.split("\n")
    cleaned_lines = []
    for line in lines:
        stripped = line.strip()
        # Drop lines that are just a number (typical page-number footer/header)
        if re.fullmatch(r"\d{1,4}", stripped):
            continue
        # Drop common footer patterns like "Page 3 of 10"
        if re.fullmatch(r"(?i)page\s+\d+(\s+of\s+\d+)?", stripped):
            continue
        cleaned_lines.append(line)
    text = "\n".join(cleaned_lines)
    # Collapse 3+ blank lines into 2, and trim trailing spaces
    text = re.sub(r"\n{3,}", "\n\n", text)
    text = re.sub(r"[ \t]+\n", "\n", text)
    return text.strip()


def _load_pdf(path: Path) -> List[Dict]:
    pages = []
    with pdfplumber.open(path) as pdf:
        for i, page in enumerate(pdf.pages, start=1):
            raw = page.extract_text() or ""
            cleaned = _clean_text(raw)
            if cleaned:
                pages.append({
                    "source": path.name,
                    "page_number": i,
                    "text": cleaned,
                })
    return pages


def _load_txt(path: Path) -> List[Dict]:
    raw = path.read_text(encoding="utf-8", errors="ignore")
    cleaned = _clean_text(raw)
    return [{"source": path.name, "page_number": 1, "text": cleaned}] if cleaned else []


def _load_docx(path: Path) -> List[Dict]:
    doc = DocxDocument(str(path))
    raw = "\n".join(p.text for p in doc.paragraphs)
    cleaned = _clean_text(raw)
    return [{"source": path.name, "page_number": 1, "text": cleaned}] if cleaned else []


def load_documents(data_dir: Path) -> List[Dict]:
    """
    Load every supported file in `data_dir` and return a flat list of page
    dicts: {"source": filename, "page_number": int, "text": str}
    """
    all_pages: List[Dict] = []
    files = sorted(p for p in data_dir.iterdir() if p.suffix.lower() in SUPPORTED_EXTENSIONS)

    if not files:
        raise FileNotFoundError(
            f"No supported documents (.pdf, .txt, .docx) found in {data_dir}"
        )

    for path in files:
        ext = path.suffix.lower()
        if ext == ".pdf":
            pages = _load_pdf(path)
        elif ext == ".txt":
            pages = _load_txt(path)
        elif ext == ".docx":
            pages = _load_docx(path)
        else:
            continue
        print(f"  Loaded {path.name}: {len(pages)} page(s)")
        all_pages.extend(pages)

    return all_pages


if __name__ == "__main__":
    from config import DATA_DIR
    docs = load_documents(DATA_DIR)
    print(f"\nTotal pages loaded: {len(docs)}")
